name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        gemfile: [ '7.0.0', '6.1.3.1', '6.0.3.6', '5.2.5', '5.1.7', '4.2.11.3' ]
        ruby: [ '3.1', '3.0', '2.7' ]
        exclude:
          - ruby: '3.1'
            gemfile: '5.2.5'
          - ruby: '3.1'
            gemfile: '5.1.7'
          - ruby: '3.1'
            gemfile: '4.2.11.3'
          - ruby: '3.0'
            gemfile: '5.2.5'
          - ruby: '3.0'
            gemfile: '5.1.7'
          - ruby: '3.0'
            gemfile: '4.2.11.3'
          - ruby: '2.7'
            gemfile: '4.2.11.3'
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }} rails-${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.gemfile }}.gemfile
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      CI: true
      RAILS_ENV: test
